### ISSUE TITLE
www.DOMAIN.tld results in "Site get failure: Site does not exist"

### ISSUE THREAD

**Issue by sebastiande** [plesk/letsencrypt-plesk#4] opened 2015-11-21 13:22 UTC
I can only run the tool for domain without www. prefix. 
So if I open the Website with www. prefix I get the browser error because the certificat is only installed for DOMAIN.tld. 

If I run letsencrypt with -d domain.tld -d www.domain.tld I get the error "Site get failure: Site does not exist"

What can I do to install certificate for www.domain.tld and domain.tld ?

**Comment by bejonwe** [comment] 2015-12-03 20:25
+1 I have the same problem.

**Comment by hbickenbach** [comment] 2015-12-03 21:38
i also ran into the same problem: I am using a certificate with domain.tld and www.domain.tld for each website in plesk. Only the domain.tld is working.

**Comment by djimno** [comment] 2015-12-04 00:03
me too

**Comment by sebastiande** [comment] 2015-12-04 17:37
still exists in the plesk extension as the extension only creates certificates for domain.tld and not for www.domain.tld

**Comment by djimno** [comment] 2015-12-04 17:42
Its right. After update of the plesk ext the error still exist. It is not posible to creat the certificates for www.domain.tld

**Comment by djimno** [comment] 2015-12-04 17:43
Pls open the issue again

**Comment by sibprogrammer** [comment] 2015-12-04 17:44
"www" prefix fix had clashed with other functionality and had been rolled back in last minute before publication. We've another idea to add option and allow explicitly define if "www" prefix is needed or not. Please wait for fix in the future releases.

**Comment by xgin** [comment] 2015-12-06 05:34
As a workaround for the extension use `sudo -u psaadm bash /usr/local/psa/admin/plib/modules/letsencrypt/scripts/le-run -d domain.tld -d www.domain.tld`
Do not run it without sudo, it becomes inoperable by Plesk.
The CLI interface is not pretty, we should improve it next version.
And sure the issue should be fixed in UI.

**Comment by cutzenfriend** [comment] 2015-12-06 11:18
+1 for a fast fix. Same issue here.

**Comment by discostur** [comment] 2015-12-06 16:38
+1 having the same problem

**Comment by djimno** [comment] 2015-12-06 18:30
It works fine now

**Comment by nicosmuts** [comment] 2015-12-07 04:10
CLI workaround is working, thanks for the fix.

Looking forward seeing it in the UI.

**Comment by xgin** [comment] 2015-12-08 12:15
The issue is completely fixed with checkbox in UI.
Check the extension version 1.1

**Closed by xgin** 2015-12-08 12:15 UTC
