### ISSUE TITLE
DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python

### ISSUE THREAD

**Issue by rorteu** [plesk/letsencrypt-plesk#87] opened 2016-03-21 11:24 UTC
Hello to everybody!

I have CentOS 6.6 with python 2.6, It seems that letsencrypt extension is using "my" python 2.6, letsencrypt extension with python does not function, is there a solution to this issue?

Thanks!

**Comment by xgin** [comment] 2016-03-22 02:12
Duplicate of #70

**Closed by xgin** 2016-03-22 02:12 UTC
