### ISSUE TITLE
Renewal issue : The client lacks sufficient authorization

### ISSUE THREAD

**Issue by Crabtronic** [plesk/letsencrypt-plesk#92] opened 2016-03-30 15:15 UTC
Hello,

I started with this error :

> Fehler: Fehler bei der Installation des 
> SSL-Zertifikats von Let's Encrypt: Failed letsencrypt execution: 
> Traceback (most recent call last):
> File "/opt/psa/var/modules/letsencrypt/venv/bin/letsencrypt", line 11, in
> sys.exit(main())
> File "/usr/local/psa/var/modules/letsencrypt/venv.9b7lw/local/lib/python2.7/site-packages/letsencrypt/cli.py",
> line 1950, in main
> plugins = plugins_disco.PluginsRegistry.find_all()
> File "/usr/local/psa/var/modules/letsencrypt/venv.9b7lw/local/lib/python2.7/site-packages/letsencrypt/plugins/disco.py",
> line 168, in find_all
> plugin_ep = PluginEntryPoint(entry_point)
> File "/usr/local/psa/var/modules/letsencrypt/venv.9b7lw/local/lib/python2.7/site-packages/letsencrypt/plugins/disco.py",
> line 31, in init
> self.plugin_cls = entry_point.load()
> File "/usr/local/psa/var/modules/letsencrypt/venv.9b7lw/local/lib/python2.7/site-packages/pkg_resources/init.py",
> line 2201, in load
> self.require(args, *kwargs)
> File "/usr/local/psa/var/modules/letsencrypt/venv.9b7lw/local/lib/python2.7/site-packages/pkg_resources/init.py",
> line 2218, in require items = working_set.resolve(reqs, env, installer)
> File "/usr/local/psa/var/modules/letsencrypt/venv.9b7lw/local/lib/python2.7/site-packages/pkg_resources/init.py", line 835, in resolve
> raise VersionConflict(dist, req).with_context(dependent_req)
> ContextualVersionConflict: (cryptography 1.1 
> (/opt/psa/var/modules/letsencrypt/venv.9b7lw/lib/python2.7/site-packages),
> Requirement.parse('cryptography>=1.3'), set(['PyOpenSSL']))

So I did this :
`sudo apt-get install build-essential libssl-dev libffi-dev python-dev`

and this:
`cd /usr/local/psa/var/modules/letsencrypt/venv/bin./pip install --upgrade cryptography`

And now I'have the problem about the acme challenge on an ubuntu 14.04 / plesk 12.5 :

> authorization procedure. mydomain.fr (http-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://mydomain.fr/.well-known/acme-challenge/6jry12LYTyHk-69Iks4HC1HHm-SPKZHE3DepDGfoH-E [my.ip]: 404, www.mydomain.fr (http-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://www.mydomain.fr/.well-known/acme-challenge/fg1wVWE8ZAvej3U9MA5yclMkKb002w7vqrrHZcGVe2E [my.ip]: 404

- I'v put an empty .htaccess file in the mydomain directory
- I've try to service apache2 reload

But nothing work ! 

![sans titre20160330181715](https://cloud.githubusercontent.com/assets/8861475/14149266/a87ad65c-f6a3-11e5-80fe-395e984c7c17.png)

Now the mydomain.fr point to 
/var/vhosts/default/htdocs 
instead of 
/var/www/vhosts/mydomain.fr/mydomain

And of course I can't renew the certificat.

Thanks to help

**Comment by Crabtronic** [comment] 2016-03-30 16:13
I've just try to uninstall / reinstall extension "Letsencrypt" and I still get the same error.

**Comment by openmatl** [comment] 2016-03-31 00:57
Have the same problem: https://github.com/plesk/letsencrypt-plesk/issues/90
No solution yet. Any ideas on how to update the certificates manually via terminal.

**Comment by xgin** [comment] 2016-03-31 01:36
Hi @Crabtronic 
> Now the mydomain.fr point to 
/var/vhosts/default/htdocs 
instead of 
/var/www/vhosts/mydomain.fr/mydomain

That means the problem is caused by the web server misconfiguration and could not be repaired with letsencrypt.
Usually helps execution: plesk sbin httpdmng --reconfigure-all

**Comment by Crabtronic** [comment] 2016-03-31 15:23
Thanks Xgin.
So I did what you suggest `plesk sbin httpdmng --reconfigure-all` and nothing change.

I still get the wrong redirect for the domain.
I still get the error to renew the certificat with letsencrypt

**Comment by xgin** [comment] 2016-03-31 17:23
@Crabtronic your domain name seems to be resolved in the IP address different than Apache listens.
```
dig A ideeshaker.fr +short
82.223.23.203

curl -H "Host:ideeshaker.fr" http://82.223.22.25
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="http://www.ideeshaker.fr/">here</a>.</p>
<hr>
<address>Apache Server at ideeshaker.fr Port 80</address>
```
Please, make sure you have chosen the same IP address in DNS and Plesk.

**Comment by Crabtronic** [comment] 2016-03-31 18:06
Argh
I didn't see it. I'm such an idiot. It was the bad ip. I've three. 
You're awesome. If one day you want to see Monaco, Nice, Villeneuve Loubet I'll be please to receive you and/or to make you the guide.

THANKS A LOT !!!!

**Comment by xgin** [comment] 2016-04-01 02:07
Glad to see the problem solved!

**Closed by xgin** 2016-04-01 02:07 UTC
