### ISSUE TITLE
Chrome: old cypher suit

### ISSUE THREAD

**Issue by peter254** [plesk/letsencrypt-plesk#62] opened 2016-01-16 17:07 UTC
I created the certificates using this extension, but chrome tells me that the website is using an old cypher suite.
It is using:
* TLS 1.2
* AES_256_CBC
* HMAC-SHA1
* ECDHE_RSA

The website is https://pburkert.com

Is there a config were the parameters for the certificate can be changed?

**Comment by xgin** [comment] 2016-01-16 17:22
Duplicate of #26 
Use http://docs.plesk.com/en-US/12.5/advanced-administration-guide-linux/pci-dss-compliance/tune-plesk-to-meet-pci-dss-on-linux.65871/

**Closed by xgin** 2016-01-16 17:22 UTC

**Comment by peter254** [comment] 2016-01-16 17:26
Thank you and sorry for not looking into the closed issues
