### ISSUE TITLE
Static Private Key

### ISSUE THREAD

**Issue by Nosxxx** [plesk/letsencrypt-plesk#156] opened 2017-03-26 08:55 UTC
Hi,
for TLSA, HPKP we need fixed Private Keys. (No new Private Keys on Renew Cert)
Please consider this in Version 2.0

Thanks.

**Comment by johnny-bit** [comment] 2017-03-26 20:13
Hi!

If I remember correctly, both TLSA DNS record and HPKP header allow you to "pin" any key on keychain, so you can generate those with LE trust chain. Obviously generating both those based on own key would be perfect.

**Comment by Nosxxx** [comment] 2017-03-27 13:49
Pls vote for this. https://plesk.uservoice.com/forums/184549-feature-suggestions/suggestions/18738874-let-s-encrypt-static-private-keys

**Comment by xgin** [comment] 2017-03-30 18:47
Duplicate of #107 
This is the great feature, I hope we implement it soon.
Continue voting on the link above!

**Closed by xgin** 2017-03-30 18:47 UTC

**Comment by guillaume-uH57J9** [comment] 2018-12-16 13:01
Hi, Static private key would be great to allow using this certificate for non-http servers. 

I have a XMPP server, and a mail server which are hosted separately from HTTPS, and are not managed through Plesk. 
Because letsencrypt-plesk always replace private keys on renewal, I'm unable to have HTTPS, XMPP and MAIL on the same domain using the same private key, and I'm forced to use separate (sub)domains to workaround this.
