### ISSUE TITLE
Webmail Compatibility: webmail.domain.com

### ISSUE THREAD

**Issue by theupriser** [plesk/letsencrypt-plesk#137] opened 2016-12-15 15:21 UTC
Hello,

Is it possible to make a function in the installer to make a certificate for the wembail too?
Since I can't edit the files because they are all encrypted there was no other choice left than to ask the developers here!

I'm sure other people are desperate for this function too.

With kind regards,

Rick Peters

**Comment by theupriser** [comment] 2016-12-15 19:40
For you guys who do want this, i've made a nice script with automatic redirection for webmail with nginx. You can find it here: https://git.upriser.nl/theupriser/PleskHTTPSWebmail

**Comment by amavarick** [comment] 2016-12-31 20:33
Developers, please re-evaluate the user's request.  Currently as designed with Plesk/Onyx and the Extension, there is already an option for the user to include the created Let's Encrypt certificate with webmail for that particular domain.  This can be done by going to the particular domain within Onyx, selecting "SSL/TLS Certificates" and then enabling the option "secure webmail."  This will take the existing certificate used for the parent domain and assign that certificate to the webmail URL.

The problem is, upon creating/updating the Let's Encrypt certificate.  It does not add the webmail subdomain to the certificate, so anyone trying to reach the webmail.yourdomain.tld will receive a certificate error.

What would be beautiful is if the user is provided the choice of selecting additional subdomains and not just WWW to the Let's Encrypt certificate request.  This can be done via CLI using the unpublished command found here:
https://talk.plesk.com/threads/how-to-secure-mail-of-domain-with-lets-encrypt.339766/#post-811899

plesk bin extension --exec letsencrypt cli.php -d YOUR-DOMAIN.COM -d www.YOUR-DOMAIN.COM -d webmail.YOUR-DOMAIN.COM -d mail.YOUR-DOMAIN.COM -d smtp.YOUR-DOMAIN.COM -d pop3.YOUR-DOMAIN.COM -d imap.YOUR-DOMAIN.COM -d lists.YOUR-DOMAIN.COM --email YOUR-EMAIL-ADRESS@YOUR-DOMAIN.COM --expand

It is my understanding that the command above will add the appended subdomains to the certificate.  I have not tested this myself yet as I don't know if it will automatically renew the new subdomains or resume to the original etc...  Thank you so much for your time and I can say without a doubt, this is my most favorite extension since a competing certificate issuer lost their trust.

**Comment by stevland** [comment] 2017-03-15 01:36
> For you guys who do want this, i've made a nice script with automatic redirection for webmail with nginx. 

I had a look at your repo. It looks really promising. I am surprised that your script has been met with so little fan fair. 

I would be keen to give this a go, but I'm bit of a linux newbie. I don't want to make changes to my setup that I may have trouble reversing.

I'm 100% confident that this works perfectly on _your_ server. But has anyone else tried it?

BTW I am running:

‪CentOS Linux 7.3.1611 (Core)‬
Plesk Onyx Version 17.0.17 Update #18
Let's Encrypt 1.9 Update #3

If I were to use this script and something went wrong, would it be as simple following the instructions in reverse?

Thanks.

**Comment by darkdragon-001** [comment] 2017-04-23 10:30
I think this is a duplicate of #37

**Comment by xgin** [comment] 2017-05-18 13:28
It is possible to secure webmail with the extension version 2.1.0
Plesk Onyx is minimal required version for the feature.

**Closed by xgin** 2017-05-18 13:28 UTC

**Comment by nothegger1** [comment] 2017-05-19 07:29
Sorry, not working correctly:

Fehler: Fehler bei der Installation des SSL-Zertifikats von Let's Encrypt: Invalid response from https://acme-v01.api.letsencrypt.org/acme/new-reg: Failed to get registration by key.
Type: urn:acme:error:serverInternal.

**Comment by xgin** [comment] 2017-05-19 07:44
@nothegger1 `urn:acme:error:serverInternal` means some problems on the CA side.
According to https://letsencrypt.status.io/ there was an incident.
Try again a bit later.
